```{block tomato-prompt}
Create a `tibble` with three columns: `food`, `vegetable`, and `color`. In
`food`, store "lettuce" and "tomato". In `vegetable`, store whether the food is
a vegetable. In `color`, store the color of the food.
```

```{r tomato-setup}
library(tibble)
```

```{r tomato, exercise = TRUE}

```

```{r tomato-solution}
tibble(
  food = c("lettuce", "tomato"),
  vegetable = c(TRUE, FALSE),
  color = c("green", "red")
)
```

```{r tomato-check}
grade_this_table()
```

```{r tomato-wrong-class}
# "class" problem
list(
  food = "lettuce",
  fruit = "TRUE",
  color = "green"
)
```

```{r tomato-wrong-names}
# "names" problem
tibble(
  food = "lettuce",
  fruit = "TRUE",
  color = "green"
)
```

```{r tomato-wrong-length}
# "dimensions" problem
tibble(
  food = "lettuce",
  vegetable = "TRUE",
  color = "green"
)
```

```{r tomato-wrong-column-class}
# "class" problem in column "vegetable"
tibble(
  food = c("lettuce", "tomato"),
  vegetable = c("TRUE", "TRUE"),
  color = c("green", "red")
)
```

```{r tomato-wrong-column-values}
# "values" problem in column "vegetable"
tibble(
  food = c("lettuce", "tomato"),
  vegetable = c(TRUE, TRUE),
  color = c("green", "red")
)
```
