#' Apply automatic grading to a problem object
#'
#' @param problem A problem generated by a `tbl_check_*()` function.
#' @inheritParams tbl_check_table
#'
#' @return A [gradethis::fail()] message.
#' @export
tbl_grade <- function(problem, max_diffs = 3) {
  if (is.null(problem)) {
    return(invisible())
  }
  
  assert_internally({
    checkmate::assert_class(problem, "tblcheck_problem")
    checkmate::assert_number(max_diffs, lower = 1)
  })
  
  message_fn <- gsub("(.*_)?(.*)", "tbl_message_\\2", problem$type)
  message_fn <- rlang::as_function(message_fn, rlang::pkg_env("tblcheck"))
  
  return_if_graded(message_fn(problem, max_diffs = max_diffs))
}
