#' Apply automatic grading to a problem object
#'
#' @param problem A problem generated by a `tbl_check_*()` function.
#' @inheritParams tbl_check_table
#' @param env The environment used for grading.
#' @param ... Additional arguments passed to [gradethis::fail()].
#'
#' @return A [gradethis::fail()] message or `NULL` invisibly.
#' @export
#' 
#' @examples
#' .result <- 1:10
#' .solution <- letters[1:10]
#' problem <- vec_check_vector()
#' tblcheck_grade(problem)
tblcheck_grade <- function(problem, max_diffs = 3, env = parent.frame(), ...) {
  UseMethod("tblcheck_grade")
}

#' @rdname tblcheck_grade
#' @export
tblcheck_grade.default <- function(
  problem, max_diffs = 3, env = parent.frame(), ...
) {
  invisible()
}

#' @rdname tblcheck_grade
#' @export
tblcheck_grade.list <- function(
  problem, max_diffs = 3, env = parent.frame(), ...
) {
  problem <- as_problem(problem)
  tblcheck_grade(problem)
}

#' @rdname tblcheck_grade
#' @export
tblcheck_grade.tblcheck_problem <- function(
  problem, max_diffs = 3, env = parent.frame(), ...
) {
  if (is.null(problem)) {
    return(invisible())
  }
  
  err <- catch_internal_problem(
    checkmate::assert_number(max_diffs, lower = 1), 
    call = find_tblcheck_call()
  )
  
  if (is_problem(err)) {
    return(tblcheck_grade(err))
  }
  
  gradethis::fail(
    tbl_message(problem, max_diffs = max_diffs),
    problem = problem,
    env = env,
    ...
  )
}

tbl_message <- function(problem, ...) {
  UseMethod("tbl_message")
}

tbl_message.default <- function(problem, ...) {
  invisible()
}

tbl_message.tblcheck_problem <- function(problem, ...) {
  type_msg <- if (!is.null(problem$type)) {
    gettext("Your code resulted in a `{type}` problem. ")
  } else {
    ""
  }
  
  exp_msg <- if (!is.null(problem$expected)) {
    expected <- paste(md_code(problem$expected), collapse = ", ")
    gettext("I was expecting a value of {expected}. ")
  } else {
    ""
  }
  
  obj_msg <- if (!is.null(problem$actual)) {
    actual <- paste(md_code(problem$actual), collapse = ", ")
    gettext("Your result gave a value of `{actual}`. ")
  } else {
    ""
  }
  
  glue::glue_data(problem, type_msg, exp_msg, obj_msg)
}
