#' Apply automatic grading to a problem object
#'
#' @param problem A problem generated by a `tbl_check_*()` function.
#' @inheritParams tbl_check
#' @param env The environment used for grading.
#' @inheritDotParams gradethis::fail -message
#'
#' @return A [gradethis::fail()] message or `NULL` invisibly.
#' @export
#'
#' @examples
#' .result <- 1:10
#' .solution <- letters[1:10]
#' problem <- vec_check()
#' problem_grade(problem)
problem_grade <- function(problem, max_diffs = 3, env = parent.frame(), ...) {
  UseMethod("problem_grade")
}

#' @rdname problem_grade
#' @export
problem_grade.default <- function(
  problem, max_diffs = 3, env = parent.frame(), ...
) {
  invisible()
}

#' @rdname problem_grade
#' @export
problem_grade.list <- function(
  problem, max_diffs = 3, env = parent.frame(), ...
) {
  problem <- as_problem(problem)
  problem_grade(problem, max_diffs = max_diffs, env = env, ...)
}

#' @rdname problem_grade
#' @export
problem_grade.tblcheck_problem <- function(
  problem, max_diffs = 3, env = parent.frame(), ...
) {
  if (is.null(problem)) {
    return(invisible())
  }

  err <- catch_internal_problem(
    checkmate::assert_number(max_diffs, lower = 1),
    call = find_tblcheck_call()
  )

  if (is_problem(err)) {
    return(problem_grade(err))
  }

  gradethis::fail(
    problem_message(problem, max_diffs = max_diffs),
    problem = problem,
    env = env,
    ...
  )
}
